version: '3.9'

x-common-variables: &common-variables
  POSTGRES_DB: postgres
  POSTGRES_USER: admin
  PGUSER: admin
  POSTGRES_PASSWORD: 123
  TZ: "America/Sao_Paulo"

services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    container_name: go-app
    restart: unless-stopped
    environment:
      <<: *common-variables
      APP_PORT: 8080
      APP_NAME: GoBotApp
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      DB_URL: mysql://admin:password123@db:3306/testbg
      # Check the video below to learn how to use gmail smtp server to send emails
      # https://www.youtube.com/watch?v=g_j6ILT-X0k
      # SMTP_EMAIL: your gmail here
      # SMTP_PSWD: our gmail passphrase here
    ports: 
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
  ### Postgreql
  # db:
  #   image: postgres:latest
  #   container_name: go-app-postgres
  #   restart: unless-stopped
  #   environment:
  #     <<: *common-variables
  #     PGTZ: "America/Sao_Paulo"
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  #   healthcheck:
  #     # https://stackoverflow.com/questions/60193781/postgres-with-docker-compose-gives-fatal-role-root-does-not-exist-error
  #     test: "pg_isready -h db"
  #     interval: 10s
  #     timeout: 15s
  #     retries: 10
  #     start_period: 10s
  ### Mysql
  db:
    image: mysql:latest
    container_name: mysql-test
    restart: unless-stopped
    ports:
      - "3306:3306"
    command: --init-file /data/application/init.sql
    volumes:
      - ./init.sql:/data/application/init.sql
    environment:
      MYSQL_DATABASE: testbg
      MYSQL_USER: admin
      MYSQL_PASSWORD: password123
      MYSQL_ROOT_PASSWORD: password123
      TZ: "America/Sao_Paulo"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 15s
      retries: 10  